server:
  port: ${PORT:8080}
logging:
  level:
    org:
      atmosphere: warn
      springframework: DEBUG
    com:
      vaadin.flow.spring: DEBUG
spring:
  application:
    name: Pure Plate
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:classpath:/data/localdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: create

    naming:
      physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mustache:
    check-template-location: false

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.pureplate

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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
